name: mesa-core22
base: core22
adopt-info: mesa
summary: mesa libraries for core20 snaps
description: |
  A content snap containing the mesa libraries and drivers for core 22
compression: lzo

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x
  - build-on: riscv64

parts:
  mesa:
    plugin: nil
    override-pull:
      craftctl set version=`LANG=C apt-cache policy libgl1-mesa-dri | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    stage-packages:
      - libgl1-mesa-dri
      - va-driver-all
      - libegl1
      - libgles2
      - libdrm2
      - libdrm-common
    organize:
      'usr/lib/${CRAFT_ARCH_TRIPLET}/dri/*': egl/dri/
      'usr/lib/${CRAFT_ARCH_TRIPLET}/*.so*': egl/lib/
      'usr/share/glvnd': egl/glvnd/
      'usr/share/libdrm': egl/libdrm/
      'usr/share/drirc.d/': egl/drirc.d/
    prime:
      - egl/lib
      - egl/dri
      - egl/glvnd
      - egl/libdrm
      - egl/drirc.d

slots:
  graphics-core22:
    interface: content
    read:
      - egl
